sonar.projectKey=noelpatata_WalletTrackerAPI_0cf0ca12-f6dd-434b-9dbd-b121383d2888
sonar.dependencyCheck.jsonReportPath=dependency-check-report/dependency-check-report.json
sonar.dependencyCheck.severity.high=7.0
sonar.dependencyCheck.severity.medium=4.0
sonar.dependencyCheck.severity.low=0.0
sonar.dependencyCheck.summarize=true
hi.file.path=hi.txt
