name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose down --volumes --remove-orphans || true

      - run: |
          cat <<EOF > .env
          DATABASE_ROOT_PASSWORD=adminadmin
          DATABASE_NAME=wallettracker
          WALLET_TRACKER_SECRET=secret
          WALLET_TRACKER_DB_USER=root
          WALLET_TRACKER_DB_HOST=db
          COMPOSE_PROFILES=db,app
          EOF

      - run: docker compose up -d --build


      - run: docker compose exec -T app pytest -v

      - if: always()
        run: docker compose down --volumes

